google_sheets:
  credentials_file: "${GOOGLE_CREDENTIALS_FILE}"
  token_file: "${GOOGLE_TOKEN_FILE:token.json}"
  oauth_port: 8080
  default_spreadsheet_id: ""
  sheet_name: "Stock_Data"
  batch_size: 100

platforms:
  tradingview:
    encoding: "utf-8"
    include_exchange_prefix: true
    supported_exchanges:
      - "NASDAQ"
      - "NYSE"
      - "AMEX"
      - "TSE"
      - "LSE"
      - "FRA"
  seekingalpha:
    default_quantity: 0
    default_cost: 0.0
    required_sheets:
      - "Summary"
      - "Ratings"
      - "Holdings"
      - "Dividends"

logging:
  level: "${LOG_LEVEL:INFO}"
  file: "${LOG_FILE:stock_cli.log}"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

conversion:
  symbol_mapping_file: "symbol_mapping.json"
  auto_detect_exchange: true
  fallback_exchange: "NASDAQ"
  preserve_sections: true

development:
  debug_mode: "${DEVELOPMENT_MODE:false}"
  test_data_dir: "tests/sample_data"
  mock_google_api: false